#!/bin/bash
# Install guide for OpenRouter/OpenAI integration

echo "🚀 Resume Optimiser - OpenRouter Setup Guide"
echo "=============================================="
echo ""

# Check current Python
echo "📍 Current Python:"
python --version
echo ""

echo "Step 1️⃣  - Install OpenAI Package"
echo "-----------------------------------"
echo "Run the following command:"
echo ""
echo "pip install openai"
echo ""
echo "OR with version lock:"
echo "pip install 'openai>=1.0.0'"
echo ""

echo "Step 2️⃣  - Set Environment Variable"
echo "-----------------------------------"
echo ""
echo "Option A: Export in terminal (temporary)"
echo "  export OPENROUTER_API_KEY='sk_your_key_here'"
echo ""
echo "Option B: Add to .env file (permanent)"
echo "  echo 'OPENROUTER_API_KEY=sk_your_key_here' >> .env"
echo ""
echo "Option C: Add to your shell profile (~/.bashrc, ~/.zshrc)"
echo "  echo 'export OPENROUTER_API_KEY=sk_your_key_here' >> ~/.bashrc"
echo "  source ~/.bashrc"
echo ""

echo "Step 3️⃣  - Get API Key from OpenRouter"
echo "-----------------------------------"
echo "1. Go to: https://openrouter.ai"
echo "2. Sign up or login"
echo "3. Go to: https://openrouter.ai/keys"
echo "4. Create a new API key"
echo "5. Copy the key starting with 'sk_'"
echo "6. Add to environment as OPENROUTER_API_KEY"
echo ""

echo "Step 4️⃣  - Verify Installation"
echo "-----------------------------------"
echo "Run this to test:"
echo ""
echo "python -c \"import openai; print(f'✓ OpenAI {openai.__version__} installed')\""
echo ""

echo "Step 5️⃣  - Restart Server"
echo "-----------------------------------"
echo "cd resumeoptimiser && python run.py"
echo ""
echo "If logs show:"
echo "  ✓ LLMService initialized successfully"
echo ""
echo "Then you're all set! 🎉"
echo ""

echo "📝 Current Environment Variables Check:"
echo "-----------------------------------"
if [ -f ".env" ]; then
    echo "✓ .env file found"
    if grep -q "OPENROUTER_API_KEY" .env; then
        echo "✓ OPENROUTER_API_KEY is set in .env"
        echo "  Value: $(grep OPENROUTER_API_KEY .env | cut -d'=' -f2)"
    else
        echo "⚠ OPENROUTER_API_KEY is NOT set in .env"
    fi
else
    echo "⚠ No .env file found"
    echo "  Create one: touch .env"
fi

echo ""
echo "📊 Expected Behavior:"
echo ""
echo "✅ With OpenAI installed:"
echo "   2026-02-17 14:30:51 - llm - INFO - ✓ JD parsed successfully with LLM"
echo ""
echo "⚠️  Without OpenAI (will use regex fallback):"
echo "   2026-02-17 14:30:51 - llm - WARNING - ⚠ OpenAI client not available"
echo "   2026-02-17 14:30:51 - generation - WARNING - Falling back to regex"
echo ""

echo "🔍 Troubleshooting:"
echo ""
echo "Q: 'openai' command not found"
echo "A: Make sure you're in the right Python environment:"
echo "   which python"
echo "   pip list | grep openai"
echo ""
echo "Q: API errors after installing"
echo "A: Check your API key:"
echo "   echo $OPENROUTER_API_KEY"
echo ""
echo "Q: Still falling back to regex"
echo "A: Check logs for detailed error:"
echo "   tail -f resumeoptimiser/logs/llm.log"
echo ""

echo "📚 Resources:"
echo "  - OpenRouter Docs: https://openrouter.ai/docs"
echo "  - OpenAI Python: https://github.com/openai/openai-python"
echo "  - Local logs: resumeoptimiser/logs/"
echo ""

echo "✨ Need help?"
echo "  Check LOGGING_AND_LLM.md for complete documentation"
echo "  Check BACKEND_IMPROVEMENTS.md for configuration options"
echo ""
